services:
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - gmapsdev:/var/lib/postgresql/data
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./scripts/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@db:5432/postgres?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["-api"]
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: "unless-stopped"
volumes:
  gmapsdev:
